// Generated by CoffeeScript 1.6.3
(function() {
  var Q, stump;

  Q = require('q');

  stump = require('stump');

  describe('EWS', function() {
    var EngineWebsocketServer, EngineWebsocketSlave, InitiatorProtocol, WebsocketInitiator, options;
    EngineWebsocketServer = require('../lib/ews/ew_server');
    EngineWebsocketSlave = require('../lib/ews/ew_slave');
    WebsocketInitiator = require('../lib/ews/ws_initiator');
    InitiatorProtocol = require('../lib/ews/i_protocol');
    options = {
      journalname: "testjournal"
    };
    beforeEach(function(finish) {
      var _this = this;
      console.log('STARTING');
      this.engine_server = new EngineWebsocketServer();
      return this.engine_server.start().then(function() {
        return finish();
      });
    });
    afterEach(function(finish) {
      var _this = this;
      console.log('CLEANING UP');
      return this.engine_server.stop().then(function() {
        return finish();
      });
    });
    it('should listen and be connectable', function(finish) {
      var wsi,
        _this = this;
      stump.info('started');
      wsi = new WebsocketInitiator({
        wsconfig: 'ws://localhost:6150/',
        protocol: new InitiatorProtocol({})
      });
      return wsi.connect().then(function() {
        return wsi.execute_operation({
          kind: "ADD_DEPOSIT",
          account: "peter",
          amount: "5",
          currency: 'BTC'
        }).then(function(retval) {
          stump.info('GOT RETVAL', retval);
          return finish();
        });
      }).done();
    });
    return xit('should replicate', function(finish) {
      var slave,
        _this = this;
      slave = new EngineWebsocketSlave({
        journalname: 'slavejournal',
        wsconfig: 'ws://localhost:6150/'
      });
      return slave.connect_upstream().then(function() {
        var wsi;
        stump.info('CONNECTED UPSTREAM');
        wsi = new WebsocketInitiator({
          wsconfig: 'ws://localhost:6150/',
          protocol: new InitiatorProtocol({})
        });
        return wsi.connect().then(function() {
          return wsi.execute_operation({
            kind: "ADD_DEPOSIT",
            account: "peter",
            amount: "5",
            currency: 'BTC'
          }).then(function(retval) {
            stump.info('GOT RETVAL', retval);
            return finish();
          });
        });
      });
    });
  });

}).call(this);
