// Generated by CoffeeScript 1.6.3
(function() {
  var TestHelper, fs;

  global.chai = require('chai');

  global.expect = chai.expect;

  global.assert = chai.assert;

  global.sinon = require('sinon');

  chai.should();

  fs = require('fs');

  chai.use(function(_chai, utils) {
    return chai.Assertion.addMethod('succeed_with', function(kind) {
      var obj;
      obj = utils.flag(this, 'object');
      this.assert(obj.status === 'success', "Expected #\{this} to have status of success but got " + obj.status, "Expected #\{this} not to have status of ");
      return this.assert(obj.kind === kind, "Expected #\{this} to have kind of " + kind + " but got " + obj.kind, "Expected #\{this} not to have kind of " + kind + " (got " + obj.kind);
    });
  });

  TestHelper = (function() {
    function TestHelper() {}

    TestHelper.clean_state_sync = function() {
      if (fs.existsSync('journal.log')) {
        fs.unlinkSync('journal.log');
      }
      if (fs.existsSync('test.log')) {
        return fs.unlinkSync('test.log');
      }
    };

    return TestHelper;

  })();

  global.TestHelper = TestHelper;

}).call(this);
