// Generated by CoffeeScript 1.6.3
(function() {
  var ApiClient, ApiServer, Connection, alice, stump,
    _this = this;

  stump = require('stump');

  ApiClient = require('./lib/ews/ew_api');

  ApiServer = require('./lib/api/server');

  Connection = require('./lib/ews/ws_connection');

  stump.stumpify(this, "[TEST]Client");

  alice = new Connection(stump);

  alice.on('open', function() {
    _this.warn("CONNECTED ALICE");
    return alice.send_obj({
      kind: 'AUTH',
      account_id: 'alice'
    }).then(function() {
      return _this.warn("SENT AUTH");
    }).fail(function(error) {
      return _this.error(error);
    }).done();
  });

  alice.on('parsed_data', function(data) {
    return _this.info("ALICE GOT:", data);
  });

  alice.connect('ws://localhost:3001');

}).call(this);
