// Generated by CoffeeScript 1.6.3
(function() {
  var BE, EngineServer, Journal, ProcessingChainEntrance, stump,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  stump = require('stump');

  BE = require('buttercoin-engine');

  Journal = BE.Journal;

  ProcessingChainEntrance = BE.ProcessingChainEntrance;

  module.exports = EngineServer = (function() {
    function EngineServer(options) {
      this.options = options;
      this.send_all = __bind(this.send_all, this);
      this.start = __bind(this.start, this);
      stump.stumpify(this, this.constructor.name);
      this.options = this.options || {};
      this.options.journalname = this.options.journalname || 'testjournal';
      this.engine = new BE.TradeEngine();
      this.journal = new BE.Journal(this.options.journalname);
      this.pce = new ProcessingChainEntrance(this.engine, this.journal);
    }

    EngineServer.prototype.start = function() {
      throw Error("Not Implemented");
    };

    EngineServer.prototype.send_all = function(obj) {
      throw Error("Not Implemented");
    };

    return EngineServer;

  })();

}).call(this);
